// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Defines a Genkit flow for defining words using AI.
 *
 * - defineWord - A function that handles the word definition process.
 * - DefineWordInput - The input type for the defineWord function.
 * - DefineWordOutput - The return type for the defineWord function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const DefineWordInputSchema = z.object({
  word: z.string().describe('The word to define.'),
});
export type DefineWordInput = z.infer<typeof DefineWordInputSchema>;

const DefineWordOutputSchema = z.object({
  definition: z.string().describe('The definition of the word.'),
});
export type DefineWordOutput = z.infer<typeof DefineWordOutputSchema>;

export async function defineWord(input: DefineWordInput): Promise<DefineWordOutput> {
  return defineWordFlow(input);
}

const prompt = ai.definePrompt({
  name: 'defineWordPrompt',
  input: {schema: DefineWordInputSchema},
  output: {schema: DefineWordOutputSchema},
  prompt: `You are a dictionary. Provide a concise definition of the following word:

Word: {{{word}}}`,
});

const defineWordFlow = ai.defineFlow(
  {
    name: 'defineWordFlow',
    inputSchema: DefineWordInputSchema,
    outputSchema: DefineWordOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
